// verdict-data.jsx — 4 fully-fleshed verdict reports spanning the buildability spectrum

const VERDICT_REPORTS = [
  // ───────── WEEKEND ─────────
  {
    id: 'notion',
    name: 'notion-ish.com',
    tagline: 'block-based docs + database',
    scannedAt: '2026.04.24 · 14:32',
    tier: 'WEEKEND',
    tierColor: '#22c55e',
    tierBg: '#dcfce7',
    score: 78,
    take: "It's a rich-text editor with a recursive database attached. The magic is the drag-handle and the schema. The rest is a CRUD app in a trenchcoat.",
    take_sub: "You will spend 80% of your time on the block editor and 20% on everything else. Plan accordingly.",
    currentCost: { label: 'Plus plan', price: 10, unit: 'seat/mo', annual: 120 },
    estCost: [
      { line: 'Vercel (hobby tier)', cost: 0 },
      { line: 'Supabase (free tier: 500MB)', cost: 0 },
      { line: 'Domain (yourself.dev)', cost: 1.00 },
      { line: 'Resend (100 emails/day free)', cost: 0 },
    ],
    estTotal: 1.00,
    breakEven: 'never — you save $119/year, forever',
    alternatives: [
      { name: 'Obsidian', why: 'local-first, free, plugin-rich. Already has the editor.' },
      { name: 'Outline (self-host)', why: 'open source, docker-up in 10 min. No blocks but hot-reload docs.' },
      { name: 'SilverBullet.md', why: 'extensible markdown notebook. Closer to Notion than you think.' },
    ],
    challenges: [
      { diff: 'easy', name: 'Basic blocks + slash menu', note: 'TipTap ships with most of this.' },
      { diff: 'medium', name: 'Recursive page tree', note: 'Parent_id column. Adjacency list. 40 lines of SQL.' },
      { diff: 'medium', name: 'Inline databases', note: 'A block that holds a query. Render as table.' },
      { diff: 'hard', name: 'Drag-to-reorder across nested lists', note: 'The only genuinely annoying part. dnd-kit gets you 80%.' },
      { diff: 'nightmare', name: 'Real-time multiplayer', note: 'Skip it. You do not need Y.js for your personal wiki.' },
    ],
    stack: ['Next.js 15 + TipTap', 'Postgres (Supabase)', 'Recursive CTE for page trees', 'Tiptap collaboration (optional)'],
    timeEstimate: '14 hours',
    timeBreakdown: '1 eve setting up · 1 weekend hacking · 4 evenings polishing',
    confidence: 92,
  },

  // ───────── WEEKEND ─────────
  {
    id: 'calendly',
    name: 'calendly-ish.com',
    tagline: 'scheduling link generator',
    scannedAt: '2026.04.24 · 14:48',
    tier: 'WEEKEND',
    tierColor: '#22c55e',
    tierBg: '#dcfce7',
    score: 86,
    take: "You're charging $12/mo for an if-statement and a calendar invite. Respect. But also, an if-statement.",
    take_sub: "The whole product is: check Google Calendar busy times, subtract from a schedule template, render the gaps as clickable buttons. That's the tweet.",
    currentCost: { label: 'Standard plan', price: 12, unit: 'user/mo', annual: 144 },
    estCost: [
      { line: 'Vercel (hobby tier)', cost: 0 },
      { line: 'Google Calendar API', cost: 0 },
      { line: 'Resend (notifications)', cost: 0 },
      { line: 'Domain', cost: 1.00 },
    ],
    estTotal: 1.00,
    breakEven: 'immediately — pays for itself on day one',
    alternatives: [
      { name: 'Cal.com (self-host)', why: 'open source. Docker-up. Genuinely feature-complete.' },
      { name: 'Zcal, SavvyCal free tier', why: 'if you want to skip the build.' },
      { name: 'A bento.me booking link', why: 'if your needs are two per week.' },
    ],
    challenges: [
      { diff: 'easy', name: 'OAuth with Google', note: 'Literally follow the quickstart.' },
      { diff: 'easy', name: 'Read busy times', note: 'One API call. freebusy.query.' },
      { diff: 'medium', name: 'Availability template UI', note: 'Weekly grid. Checkboxes. Done.' },
      { diff: 'medium', name: 'Timezone math', note: 'Use Luxon. Do not roll your own. Please.' },
      { diff: 'hard', name: 'Round-robin team scheduling', note: 'Only if you have a team. You do not.' },
    ],
    stack: ['Next.js + form actions', 'Google Calendar API (freebusy)', 'Resend for emails', 'SQLite via Turso'],
    timeEstimate: '9 hours',
    timeBreakdown: '1 Saturday morning, minus a coffee break',
    confidence: 95,
  },

  // ───────── MONTH ─────────
  {
    id: 'linear',
    name: 'linear-ish.app',
    tagline: 'issue tracker for software teams',
    scannedAt: '2026.04.24 · 15:11',
    tier: 'MONTH',
    tierColor: '#eab308',
    tierBg: '#fef9c3',
    score: 52,
    take: "The bug tracker is a weekend. The feel is a month. You're not rebuilding Linear — you're rebuilding the 60fps keyboard-driven UI that makes Linear feel like Linear. That's the whole product.",
    take_sub: "Everything Linear does that Jira doesn't is vibes. Vibes take time.",
    currentCost: { label: 'Standard plan', price: 8, unit: 'user/mo', annual: 96, note: '× team size' },
    estCost: [
      { line: 'Vercel Pro (for edge + analytics)', cost: 20.00 },
      { line: 'Supabase Pro (>500MB likely)', cost: 25.00 },
      { line: 'Tauri bundler (free)', cost: 0 },
      { line: 'Sentry (self-host or free tier)', cost: 0 },
      { line: 'Domain + CDN', cost: 2.00 },
    ],
    estTotal: 47.00,
    breakEven: '6 team members — $48 vs $48. 10+ seats and you are laughing.',
    alternatives: [
      { name: 'Plane (self-host)', why: 'open source Linear clone. Already exists. Docker compose up.' },
      { name: 'GitHub Projects', why: 'free with your repo. Already has keyboard shortcuts.' },
      { name: 'Height (cheap alternative)', why: 'if you want the vibe without the build.' },
    ],
    challenges: [
      { diff: 'easy', name: 'Issues, statuses, assignees', note: 'CRUD app. You could write this in your sleep.' },
      { diff: 'medium', name: 'Command palette (Cmd-K)', note: 'cmdk library. Half a day to wire up 40 commands.' },
      { diff: 'medium', name: 'Keyboard navigation everywhere', note: 'Roving tabindex. Every single view. This is the slog.' },
      { diff: 'hard', name: 'Local-first sync', note: 'Electric SQL or Replicache. This is half the build time.' },
      { diff: 'hard', name: '60fps everything', note: 'Virtualized lists. Optimistic updates. Suspense boundaries. Sweat.' },
      { diff: 'nightmare', name: 'The exact motion curves', note: 'You will copy them from the real site. Everyone does.' },
    ],
    stack: ['Next.js + React Router 7', 'Postgres + ElectricSQL', 'cmdk + dnd-kit + framer-motion', 'Tauri for desktop'],
    timeEstimate: '6 weeks',
    timeBreakdown: '1 weekend working · 5 weekends polishing · 3 weekends hating yourself',
    confidence: 74,
  },

  // ───────── DON'T ─────────
  {
    id: 'stripe',
    name: 'stripe-ish.com',
    tagline: 'payments infrastructure',
    scannedAt: '2026.04.24 · 15:29',
    tier: "DON'T",
    tierColor: '#ef4444',
    tierBg: '#fee2e2',
    score: 6,
    take: "Absolutely not. This is the one thing on the internet that is genuinely worth paying for. Put your laptop down. Go outside.",
    take_sub: "You are not going to get PCI DSS Level 1 certified this weekend. You are not going to negotiate interchange with Visa. You are going to pay Stripe 2.9% + 30¢ and you are going to like it.",
    currentCost: { label: 'Standard rate', price: '2.9% + $0.30', unit: 'per txn', annual: 'scales w/ GMV', note: 'no seat fees, no monthly minimum' },
    estCost: [
      { line: 'PCI DSS Level 1 audit', cost: 50000 },
      { line: 'Acquiring bank relationship', cost: '???' },
      { line: 'Compliance & legal counsel', cost: 120000 },
      { line: 'Fraud detection infra', cost: 2000 },
      { line: 'Your remaining sanity', cost: 'priceless' },
    ],
    estTotal: 172000,
    breakEven: 'approximately never',
    alternatives: [
      { name: 'Stripe', why: 'yes, we are recommending the thing you scanned. That\'s how good it is.' },
      { name: 'Lemon Squeezy', why: 'merchant of record, handles tax, 5% flat. For digital goods.' },
      { name: 'Paddle', why: 'same deal. MoR model. Lets you pretend you don\'t have customers in Germany.' },
    ],
    challenges: [
      { diff: 'nightmare', name: 'PCI DSS compliance', note: 'A 12-page SAQ is the easy version. Level 1 is an on-site audit.' },
      { diff: 'nightmare', name: 'Acquiring bank partnerships', note: 'You need one. They will not call you back.' },
      { diff: 'nightmare', name: 'Fraud detection', note: 'You will lose more to fraud than you make in revenue.' },
      { diff: 'nightmare', name: 'International money movement', note: 'Money transmitter licenses. Per state. In the US. Alone.' },
      { diff: 'nightmare', name: 'Being regulated', note: 'Hope you like the word "custodian".' },
      { diff: 'nightmare', name: 'Chargebacks', note: 'You are the bank now. Have fun.' },
    ],
    stack: ['regulatory attorneys ($800/hr)', 'a bank (several, actually)', 'SOC 2 + PCI DSS', 'your remaining tears'],
    timeEstimate: '∞',
    timeBreakdown: 'Patrick started in 2010. Still working on it.',
    confidence: 99,
  },
];

window.VERDICT_REPORTS = VERDICT_REPORTS;
